language: python

dist: xenial
install: pip install --upgrade pip tox virtualenv

matrix:
    include:
        - python: 3.7
          env:
            - TOXENV=flake8
        - python: 3.7
          env:
            - TOXENV=py37
        - python: 3.8
          env:
            - TOXENV=py38

script:
  - cd asgilook/
  - tox
